cmake_minimum_required(VERSION 4.1)
project(DSA)

set(CMAKE_CXX_STANDARD 17)


add_executable(Codeforces_Desorting Codeforces_Desorting.cpp)
add_executable(Codeforces_Forbidden_Integer Codeforces_Forbidden_Integer.cpp )
add_executable(Codeforces_Grasshopper_on_a_Line Codeforces_Grasshopper_on_a_Line.cpp)
add_executable(Codeforces_Unit_Array Codeforces_Unit_Array.cpp)
add_executable(Codeforces_Twin_Permutations Codeforces_Twin_Permutations.cpp)
add_executable(Codeforces_Blank_Space Codeforces_Blank_Space.cpp)
add_executable(Codeforces_Coins Codeforces_Coins.cpp)
add_executable(Codeforces_Walking_Master Codeforces_Walking_Master.cpp)
add_executable(Codeforces_We_Need_The_Zero Codeforces_We_Need_The_Zero.cpp)
add_executable(Codeforces_Prepend_And_Append Codeforces_Prepend_And_Append.cpp)
add_executable(Codeforces_Several_Mocha_Arrays Codeforces_Several_Mocha_Arrays.cpp)
add_executable(Codeforces_One_And_Two Codeforces_One_And_Two.cpp)
add_executable(Codeforces_Make_It_Beautiful Codeforces_Make_It_Beautiful.cpp)
add_executable(Codeforces_Everybody_Likes_A_Good_Array Codeforces_Everybody_Likes_A_Good_Array.cpp)
add_executable(Codeforces_Extremely_Round Codeforces_Extremely_Round.cpp)
add_executable(Codeforces_Two_Permutation Codeforces_Two_Permutation.cpp)
add_executable(Codeforces_Forked Codeforces_Forked.cpp)
add_executable(Codeforces_Chemistry Codeforces_Chemistry.cpp)
add_executable(scrap scrap.cpp)
add_executable(Codeforces_Vasijile Codeforces_Vasijile.cpp)
add_executable(Codeforces_Jellyfish Codeforces_Jellyfish.cpp)
add_executable(Codeforces_Make_It_Zero Codeforces_Make_It_Zero.cpp)
add_executable(Codeforces_Longest_Divisor_Internal Codeforces_Longest_Divisor_Internal.cpp)
add_executable(Codeforces_Balanced_Round Codeforces_Balanced_Round.cpp)
add_executable(Codeforces_Comparision_String Codeforces_Comparision_String.cpp)
add_executable(Codeforces_Permutation_Swap Codeforces_Permutation_Swap.cpp)
add_executable(Codeforces_Next_round Codeforces_Next_round.cpp)
add_executable(Codeforces_Odd_Queries Codeforces_Odd_Queries.cpp)
add_executable(Codeforces_Not_Dividing Codeforces_Not_Dividing.cpp)
add_executable(Codeforces_Mainak_And_Array Codeforces_Mainak_And_Array.cpp)
add_executable(Codeforces_NIT Codeforces_NIT.cpp)
add_executable(Codeforces_AvtoBus Codeforces_AvtoBus.cpp)
add_executable(Codeforces_Make_It_Increasing Codeforces_Make_It_Increasing.cpp)
add_executable(Codeforces_Deletive_Editing Codeforces_Deletive_Editing.cpp)
add_executable(Codeforces_Array_Cloning Codeforces_Array_Cloning.cpp)
add_executable(Codeforces_MakeAP Codeforces_MakeAP.cpp)
add_executable(Eating_Game Eating_Game.cpp)
add_executable(Codeforces_Deletion_Sort Codeforces_Deletion_Sort.cpp)
add_executable(Codeforces_Specialty_String Codeforces_Specialty_String.cpp)
add_executable(Codeforces_Portal Codeforces_Portal.cpp)
add_executable(Codeforces_Divisive_Battle Codeforces_Divisive_Battle.cpp)
add_executable(Codeforces_Odd_Grasshopper Codeforces_Odd_Grasshopper.cpp)
add_executable(Codeforces_AB_Balance Codeforces_AB_Balance.cpp)
add_executable(Codeforces_Make_Divisible Codeforces_Make_Divisible.cpp)
add_executable(Codeforces_Luntik_and_Subsequences Codeforces_Luntik_and_Subsequences.cpp)
add_executable(Codeforces_Exciting_Bets Codeforces_Exciting_Bets.cpp)
add_executable(Codeforces_Bad_boy Codeforces_Bad_boy.cpp)
add_executable(Codeforces_Odd_Divisor Codeforces_Odd_Divisor.cpp)
add_executable(Codeforces_Strange_Partition Codeforces_Strange_Partition.cpp)
add_executable(Codeforces_Sum_Of_Medians Codeforces_Sum_Of_Medians.cpp)
add_executable(Codeforces_Three_Indices Codeforces_Three_Indices.cpp)
add_executable(Codeforces_01Game Codeforces_01Game.cpp)
add_executable(Codeforces_2_by_6 Codeforces_2_by_6.cpp)
add_executable(Codeforces_Raspberries Codeforces_Raspberries.cpp)
add_executable(Codeforces_Pak_Chanesk Codeforces_Pak_Chanesk.cpp)
add_executable(Codeforces_Olya Codeforces_Olya.cpp)
add_executable(Codeforces_Ski_Resort Codeforces_Ski_Resort.cpp)
add_executable(Codeforces_Distinct_Split Codeforces_Distinct_Split.cpp)
add_executable(Codeforces_Basketball_Together Codeforces_Basketball_Together.cpp)
add_executable(Codeforces_Beautiful_Array Codeforces_Beautiful_Array.cpp)
add_executable(Codeforces_Shoe_Shuffling Codeforces_Shoe_Shuffling.cpp)
add_executable(Codeforces_Promo Codeforces_Promo.cpp)
add_executable(Codeforces_MEX Codeforces_MEX.cpp)
add_executable(Codeforces_Reverse Codeforces_Reverse.cpp)
add_executable(Codeforces_Bogosort Codeforces_Bogosort.cpp)
add_executable(Codeforces_Bracket Codeforces_Bracket.cpp)
add_executable(Codeforces_Fair Codeforces_Fair.cpp)
add_executable(Codeforces_Number_Box Codeforces_Number_Box.cpp)
add_executable(Codeforces_Divisors Codeforces_Divisors.cpp)
add_executable(Codeforces_MEX2 Codeforces_MEX2.cpp)
add_executable(Codeforces_BW Codeforces_BW.cpp)
add_executable(Codeforces_JohnnyAncient Codeforces_JohnnyAncient.cpp)
add_executable(Codeforces_Buying_Torches Codeforces_Buying_Torches.cpp)
add_executable(Codeforces_array_merge Codeforces_array_merge.cpp)
add_executable(Codeforces_Swap_Delete Codeforces_Swap_Delete.cpp)
add_executable(Codeforces_Minimum_LCM Codeforces_Minimum_LCM.cpp)
add_executable(Codeforces_Traffc_Light Codeforces_Traffc_Light.cpp)
add_executable(Codeforces_Double_String Codeforces_Double_String.cpp)
add_executable(Codeforces_Divan  Codeforces_Divan.cpp)
add_executable(Codeforces_Passing_The_Ball Codeforces_Passing_The_Ball.cpp)
add_executable(Codeforces_Right_Max Codeforces_Right_Max.cpp)
add_executable(Codeforces_Spring Codeforces_Spring.cpp)
add_executable(Codeforces_Cover Codeforces_Cover.cpp)
add_executable(Codeforces_Target Codeforces_Target.cpp)
add_executable(Codeforces_Array_Coloring Codeforces_Array_Coloring.cpp)
add_executable(Codeforces_Card_deck Codeforces_Card_deck.cpp)
add_executable(Codeforces_FlipFlops Codeforces_FlipFlops.cpp)
add_executable(Codeforces_Array Codeforces_Array.cpp)
add_executable(Codeforces_CollectingGame.cpp Codeforces_CollectingGame.cpp)
add_executable(Codeforces_Yarik Codeforces_Yarik.cpp)
add_executable(Codeforces_Twins Codeforces_Twins.cpp)
add_executable(Codeforces_Counting Codeforces_Counting.cpp)
add_executable(Codeforces_LiHua Codeforces_LiHua.cpp)
add_executable(Codeforces_TeleportesI Codeforces_TeleportesI.cpp)
add_executable(Codeforces_Deja_Vu Codeforces_Kill_Demodogs.cpp)
add_executable(Codeforces_Eating_Candies Codeforces_Eating_Candies.cpp)
add_executable(Codeforces_GCDPartition Codeforces_GCDPartition.cpp)
add_executable(Codeforces_Coprime Codeforces_Coprime.cpp)
add_executable(Codeforces_Negatives_and_Positives Codeforces_Negatives_and_Positives.cpp)
add_executable(Codeforces_Mickey_Mouse_Constructive Codeforces_Mickey_Mouse_Constructive.cpp)
add_executable(Codeforces_A_Simple_Sequence Codeforces_A_Simple_Sequence.cpp)
add_executable(Codeforces_Charis Codeforces_Charis.cpp)
add_executable(Codeforces_Simple_GCD Codeforces_Simple_GCD.cpp)
add_executable(Codeforces_Taxi Codeforces_Taxi.cpp)
add_executable(Codeforces_Paint Codeforces_Paint.cpp)
add_executable(Codeforces_Q1 Codeforces_Q1.cpp)
add_executable(Codeforces_Q2 Codeforces_Q2.cpp)
add_executable(Codeforces_Needle Codeforces_Needle.cpp)
add_executable(Codeforces_Subtract_Operation Codeforces_Subtract_Operation.cpp)
add_executable(Codeforces_Perfect_Balance Codeforces_Perfect_Balance.cpp)
add_executable(Codeforces_Equalizer Codeforces_Equalizer.cpp)
add_executable(Codeforces_Aquarium Codeforces_Aquarium.cpp)
add_executable(Codeforces_2D_travelling Codeforces_2D_travelling.cpp)
add_executable(Codeforces_11 Codeforces_11.cpp)
add_executable(Understanding_Binary_Trees Understanding_Binary_Trees.cpp)
add_executable(Codeforces_Assembly Codeforces_Assembly.cpp)
add_executable(Testing Testing.cpp)